/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  ThemeSelector as ThemeSelector
} from './components/theme-selector/theme-selector';

declare global {
  interface HTMLThemeSelectorElement extends ThemeSelector, HTMLElement {
  }
  var HTMLThemeSelectorElement: {
    prototype: HTMLThemeSelectorElement;
    new (): HTMLThemeSelectorElement;
  };
  interface HTMLElementTagNameMap {
    "theme-selector": HTMLThemeSelectorElement;
  }
  interface ElementTagNameMap {
    "theme-selector": HTMLThemeSelectorElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "theme-selector": JSXElements.ThemeSelectorAttributes;
    }
  }
  namespace JSXElements {
    export interface ThemeSelectorAttributes extends HTMLAttributes {
      themeData?: { name: string, url: string }[];
    }
  }
}

